### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [RavenbornJB/OP-homework#1]
Від Вас не було ні одного запитання. Немає ідеї - немає теми.

**Comment by RavenbornJB** [comment]
Слава Ісусу Христу! Ні, я задавав запитання у Teams, але дослідження по ньому зайшли в глухий кут. Проте я вже визначився з темою дослідження, і якомога швидше закину всі дописи по ньому на гітхаб. Постараюсь зробити до сьогоднішнього вечора. Дякую за інформацію.

**Comment by RavenbornJB** [comment]
Можливо, доведеться відкласти здачу на ранок суботи, оскільки у мене (живу в селі) відключили інтернет. Пишу з мобільного, але він також дуже слабий, ледь 3g витягує

**Comment by anrom7** [comment]
Мова документів повинна бути діловою, а не сленговою.
Тема: Підбір комп'ютерних ігор на основі профілю користувача.
