### ISSUE TITLE
ДЗ2

### ISSUE THREAD

**Issue by anrom7** [RavenbornJB/OP-homework#2]
не знайшов

**Comment by RavenbornJB** [comment]
Прошу вибачення, це моя вина. писав сам текст в Google Docs, і забув завантажити його сюди. Текст вже на місці.

**Comment by anrom7** [comment]
тепер з форматуванням попрацюйте щоб хтось хотів читати Ваш текст.

**Comment by RavenbornJB** [comment]
Простіше було би якби гугл документ залінкував, так все форматування злетіло...
Зараз дороблю, дякую.
